CREATE TABLE PRODUCER(
PRODUCER_ID VARCHAR2(15) PRIMARY KEY,
PW VARCHAR2(15) NOT NULL,
NAME VARCHAR(15) NOT NULL,
ADDRESS VARCHAR2(150) NOT NULL UNIQUE,
PHONE VARCHAR2(13) NOT NULL UNIQUE
)

CREATE TABLE SYOUBINN(
SYOUBINN_ID NUMBER PRIMARY KEY,
SYURUI VARCHAR2(30),
NAME VARCHAR2(30),
PRICE NUMBER,
PRODUCER_ID VARCHAR2(15),
LIST_ID NUMBER,
CONSTRAINT FK_PRODUCER_ID FOREIGN KEY(PRODUCER_ID) REFERENCES PRODUCER(PRODUCER_ID),
CONSTRAINT FK_LIST_ID FOREIGN KEY(LIST_ID) REFERENCES SYOUBINN_LIST(LIST_ID)
)

CREATE TABLE SYOUBINN_LIST(
LIST_ID NUMBER PRIMARY KEY,
TYUUMON_ID NUMBER,
CONSTRAINT FK_TYUUMON_ID FOREIGN KEY(TYUUMON_ID)REFERENCES TYUUMON(TYUUMON_ID)
)

CREATE TABLE TYUUMON(
TYUMON_ID NUMBER PRIMARY KEY,
CONSUMER_ID VARCHAR(15),
BILL_ID NUMBER, 
CONSTRAINT FK_CONSUMER_ID FOREIGN KEY(CONSUMER_ID) REFERENCES CONSUMER(CONSUMER_ID),
CONSTRAINT FK_BILL_ID FOREIGN KEY(BILL_ID)REFERENCES BILL(BILL_ID)
)

CREATE TABLE CONSUMER(
CONSUMER_ID VARCHAR2(15) PRIMARY KEY,
PW VARCHAR2(15) NOT NULL,
NAME VARCHAR2(15) NOT NULL,
ADDRESS VARCHAR2(150) NOT NULL UNIQUE,
PHONE VARCHAR2(13) NOT NULL UNIQUE
)

CREATE TABLE BILL(
BILL_ID NUMBER PRIMARY KEY,
CUNSUMER_ID VARCHAR2(15),
PRODUCER_ID VARCHAR2(15),
CONSTRAINT FK_CONSUMER_ID FOREIGN KEY(CONSUMER_ID) REFERENCES CONSUMER(CONSUMER_ID),
CONSTRAINT FK_PRODUCER_ID FOREIGN KEY(PRODUCER_ID) REFERENCES PRODUCER(PRODUCER_ID)
)